"""empty message

Revision ID: 401b83f90bbd
Revises: 5171b2372373
Create Date: 2023-09-19 13:17:32.092624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '401b83f90bbd'
down_revision = '5171b2372373'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###
