"""empty message

Revision ID: 5171b2372373
Revises: f47bd76f49e9
Create Date: 2023-09-19 13:16:16.998835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5171b2372373'
down_revision = 'f47bd76f49e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website_link', sa.String(length=120), nullable=True))
        batch_op.drop_column('website')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.drop_column('website_link')

    # ### end Alembic commands ###
