"""Venue - artist.id foreignKey

Revision ID: 79741ad0436d
Revises: 19c2b597449e
Create Date: 2023-12-11 13:19:23.037148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79741ad0436d'
down_revision = '19c2b597449e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'Artist', ['artist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Venue', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###
